CREATE TABLE [dbo].[tblUlkeler](
	[id] [int] NOT NULL,
	[plaka] [nvarchar](150) NULL,
	[CountryEn] [nvarchar](150) NULL,
	[alankodu] [int] NULL,
	[CountryTr] [nvarchar](150) NULL,
 CONSTRAINT [PK_tblUlkeler] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (1, N'AF', N'Afghanistan', 93, N'Afganistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (2, N'AL', N'Albania', 355, N'Arnavutluk')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (3, N'DZ', N'Algeria', 213, N'Cezayir')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (4, N'AS', N'American Samoa', 1684, N'Amerikan Samoası')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (5, N'AD', N'Andorra', 376, N'Andorra')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (6, N'AO', N'Angola', 244, N'Angola')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (7, N'AI', N'Anguilla', 1264, N'Anguilla')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (8, N'AQ', N'Antarctica', 0, N'Antarktika')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (9, N'AG', N'Antigua And Barbuda', 1268, N'Antigua ve Barbuda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (10, N'AR', N'Argentina', 54, N'Arjantin')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (11, N'AM', N'Armenia', 374, N'Ermenistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (12, N'AW', N'Aruba', 297, N'Aruba')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (13, N'AU', N'Australia', 61, N'Avustralya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (14, N'AT', N'Austria', 43, N'Avusturya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (15, N'AZ', N'Azerbaijan', 994, N'Azerbaycan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (16, N'BS', N'Bahamas The', 1242, N'Bahamalar')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (17, N'BH', N'Bahrain', 973, N'Bahreyn')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (18, N'BD', N'Bangladesh', 880, N'Bangladeş')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (19, N'BB', N'Barbados', 1246, N'Barbados')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (20, N'BY', N'Belarus', 375, N'Belarus')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (21, N'BE', N'Belgium', 32, N'Belçika')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (22, N'BZ', N'Belize', 501, N'Belize')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (23, N'BJ', N'Benin', 229, N'Benin')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (24, N'BM', N'Bermuda', 1441, N'Bermuda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (25, N'BT', N'Bhutan', 975, N'Butan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (26, N'BO', N'Bolivia', 591, N'Bolivya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (27, N'BA', N'Bosnia and Herzegovina', 387, N'Bosna-Hersek')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (28, N'BW', N'Botswana', 267, N'Botsvana')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (29, N'BV', N'Bouvet Island', 0, N'Bouvet Adası')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (30, N'BR', N'Brazil', 55, N'Brezilya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (31, N'IO', N'British Indian Ocean Territory', 246, N'Britanya Hint Okyanusu Toprakları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (32, N'BN', N'Brunei', 673, N'Brunei')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (33, N'BG', N'Bulgaria', 359, N'Bulgaristan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (34, N'BF', N'Burkina Faso', 226, N'Burkina Faso')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (35, N'BI', N'Burundi', 257, N'Burundi')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (36, N'KH', N'Cambodia', 855, N'Kamboçya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (37, N'CM', N'Cameroon', 237, N'Kamerun')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (38, N'CA', N'Canada', 1, N'Kanada')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (39, N'CV', N'Cape Verde', 238, N'Cape Verde')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (40, N'KY', N'Cayman Islands', 1345, N'Cayman Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (41, N'CF', N'Central African Republic', 236, N'Orta Afrika Cumhuriyeti')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (42, N'TD', N'Chad', 235, N'Çad')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (43, N'CL', N'Chile', 56, N'Şili')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (44, N'CN', N'China', 86, N'Çin')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (45, N'CX', N'Christmas Island', 61, N'Christmas Adası')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (46, N'CC', N'Cocos (Keeling) Islands', 672, N'Cocos (Keeling) Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (47, N'CO', N'Colombia', 57, N'Kolombiya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (48, N'KM', N'Comoros', 269, N'Komorlar')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (49, N'CG', N'Republic Of The Congo', 242, N'Kongo - Brazavil')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (50, N'CD', N'Democratic Republic Of The Congo', 242, N'Kongo - Kinşasa')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (51, N'CK', N'Cook Islands', 682, N'Cook Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (52, N'CR', N'Costa Rica', 506, N'Kosta Rika')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (53, N'CI', N'Cote Ivoire (Ivory Coast)', 225, N'Côte d’Ivoire')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (54, N'HR', N'Croatia (Hrvatska)', 385, N'Hırvatistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (55, N'CU', N'Cuba', 53, N'Küba')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (56, N'CY', N'Cyprus', 357, N'Kıbrıs')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (57, N'CZ', N'Czech Republic', 420, N'Çekya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (58, N'DK', N'Denmark', 45, N'Danimarka')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (59, N'DJ', N'Djibouti', 253, N'Cibuti')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (60, N'DM', N'Dominica', 1767, N'Dominika')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (61, N'DO', N'Dominican Republic', 1809, N'Dominik Cumhuriyeti')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (62, N'TP', N'East Timor', 670, N'Doğu Timor')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (63, N'EC', N'Ecuador', 593, N'Ekvador')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (64, N'EG', N'Egypt', 20, N'Mısır')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (65, N'SV', N'El Salvador', 503, N'El Salvador')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (66, N'GQ', N'Equatorial Guinea', 240, N'Ekvator Ginesi')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (67, N'ER', N'Eritrea', 291, N'Eritre')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (68, N'EE', N'Estonia', 372, N'Estonya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (69, N'ET', N'Ethiopia', 251, N'Etiyopya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (70, N'XA', N'External Territories of Australia', 61, N'Avustralya''nın Dış Bölgeleri')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (71, N'FK', N'Falkland Islands', 500, N'Falkland Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (72, N'FO', N'Faroe Islands', 298, N'Faroe Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (73, N'FJ', N'Fiji Islands', 679, N'Fiji')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (74, N'FI', N'Finland', 358, N'Finlandiya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (75, N'FR', N'France', 33, N'Fransa')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (76, N'GF', N'French Guiana', 594, N'Fransız Guyanası')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (77, N'PF', N'French Polynesia', 689, N'Fransız Polinezyası')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (78, N'TF', N'French Southern Territories', 0, N'Fransız Güney Toprakları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (79, N'GA', N'Gabon', 241, N'Gabon')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (80, N'GM', N'Gambia The', 220, N'Gambiya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (81, N'GE', N'Georgia', 995, N'Gürcistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (82, N'DE', N'Germany', 49, N'Almanya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (83, N'GH', N'Ghana', 233, N'Gana')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (84, N'GI', N'Gibraltar', 350, N'Cebelitarık')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (85, N'GR', N'Greece', 30, N'Yunanistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (86, N'GL', N'Greenland', 299, N'Grönland')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (87, N'GD', N'Grenada', 1473, N'Grenada')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (88, N'GP', N'Guadeloupe', 590, N'Guadeloupe')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (89, N'GU', N'Guam', 1671, N'Guam')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (90, N'GT', N'Guatemala', 502, N'Guatemala')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (91, N'XU', N'Guernsey and Alderney', 44, N'Guernsey ve Alderney')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (92, N'GN', N'Guinea', 224, N'Gine')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (93, N'GW', N'Guinea-Bissau', 245, N'Gine-Bissau')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (94, N'GY', N'Guyana', 592, N'Guyana')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (95, N'HT', N'Haiti', 509, N'Haiti')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (96, N'HM', N'Heard and McDonald Islands', 0, N'Heard Adası ve McDonald Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (97, N'HN', N'Honduras', 504, N'Honduras')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (98, N'HK', N'Hong Kong S.A.R.', 852, N'Çin Hong Kong ÖİB')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (99, N'HU', N'Hungary', 36, N'Macaristan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (100, N'IS', N'Iceland', 354, N'İzlanda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (101, N'IN', N'India', 91, N'Hindistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (102, N'ID', N'Indonesia', 62, N'Endonezya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (103, N'IR', N'Iran', 98, N'İran')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (104, N'IQ', N'Iraq', 964, N'Irak')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (105, N'IE', N'Ireland', 353, N'İrlanda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (106, N'IL', N'Israel', 972, N'İsrail')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (107, N'IT', N'Italy', 39, N'İtalya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (108, N'JM', N'Jamaica', 1876, N'Jamaika')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (109, N'JP', N'Japan', 81, N'Japonya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (110, N'XJ', N'Jersey', 44, N'Jersey')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (111, N'JO', N'Jordan', 962, N'Ürdün')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (112, N'KZ', N'Kazakhstan', 7, N'Kazakistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (113, N'KE', N'Kenya', 254, N'Kenya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (114, N'KI', N'Kiribati', 686, N'Kiribati')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (115, N'KP', N'Korea North', 850, N'Kuzey Kore')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (116, N'KR', N'Korea South', 82, N'Güney Kore')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (117, N'KW', N'Kuwait', 965, N'Kuveyt')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (118, N'KG', N'Kyrgyzstan', 996, N'Kırgızistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (119, N'LA', N'Laos', 856, N'Laos')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (120, N'LV', N'Latvia', 371, N'Letonya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (121, N'LB', N'Lebanon', 961, N'Lübnan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (122, N'LS', N'Lesotho', 266, N'Lesotho')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (123, N'LR', N'Liberia', 231, N'Liberya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (124, N'LY', N'Libya', 218, N'Libya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (125, N'LI', N'Liechtenstein', 423, N'Liechtenstein')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (126, N'LT', N'Lithuania', 370, N'Litvanya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (127, N'LU', N'Luxembourg', 352, N'Lüksemburg')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (128, N'MO', N'Macau S.A.R.', 853, N'Çin Makao ÖİB')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (129, N'MK', N'Macedonia', 389, N'Kuzey Makedonya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (130, N'MG', N'Madagascar', 261, N'Madagaskar')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (131, N'MW', N'Malawi', 265, N'Malavi')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (132, N'MY', N'Malaysia', 60, N'Malezya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (133, N'MV', N'Maldives', 960, N'Maldivler')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (134, N'ML', N'Mali', 223, N'Mali')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (135, N'MT', N'Malta', 356, N'Malta')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (136, N'XM', N'Man (Isle of)', 44, N'Man Adası')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (137, N'MH', N'Marshall Islands', 692, N'Marshall Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (138, N'MQ', N'Martinique', 596, N'Martinik')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (139, N'MR', N'Mauritania', 222, N'Moritanya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (140, N'MU', N'Mauritius', 230, N'Mauritius')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (141, N'YT', N'Mayotte', 269, N'Mayotte')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (142, N'MX', N'Mexico', 52, N'Meksika')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (143, N'FM', N'Micronesia', 691, N'Mikronezya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (144, N'MD', N'Moldova', 373, N'Moldova')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (145, N'MC', N'Monaco', 377, N'Monako')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (146, N'MN', N'Mongolia', 976, N'Moğolistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (147, N'MS', N'Montserrat', 1664, N'Montserrat')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (148, N'MA', N'Morocco', 212, N'Fas')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (149, N'MZ', N'Mozambique', 258, N'Mozambik')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (150, N'MM', N'Myanmar', 95, N'Myanmar (Burma)')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (151, N'NA', N'Namibia', 264, N'Namibya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (152, N'NR', N'Nauru', 674, N'Nauru')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (153, N'NP', N'Nepal', 977, N'Nepal')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (154, N'AN', N'Netherlands Antilles', 599, N'Hollanda Antilleri')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (155, N'NL', N'Netherlands The', 31, N'Hollanda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (156, N'NC', N'New Caledonia', 687, N'Yeni Kaledonya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (157, N'NZ', N'New Zealand', 64, N'Yeni Zelanda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (158, N'NI', N'Nicaragua', 505, N'Nikaragua')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (159, N'NE', N'Niger', 227, N'Nijer')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (160, N'NG', N'Nigeria', 234, N'Nijerya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (161, N'NU', N'Niue', 683, N'Niue')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (162, N'NF', N'Norfolk Island', 672, N'Norfolk Adası')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (163, N'MP', N'Northern Mariana Islands', 1670, N'Kuzey Mariana Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (164, N'NO', N'Norway', 47, N'Norveç')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (165, N'OM', N'Oman', 968, N'Umman')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (166, N'PK', N'Pakistan', 92, N'Pakistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (167, N'PW', N'Palau', 680, N'Palau')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (168, N'PS', N'Palestinian Territory Occupied', 970, N'Filistin Bölgeleri')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (169, N'PA', N'Panama', 507, N'Panama')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (170, N'PG', N'Papua new Guinea', 675, N'Papua Yeni Gine')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (171, N'PY', N'Paraguay', 595, N'Paraguay')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (172, N'PE', N'Peru', 51, N'Peru')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (173, N'PH', N'Philippines', 63, N'Filipinler')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (174, N'PN', N'Pitcairn Island', 0, N'Pitcairn Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (175, N'PL', N'Poland', 48, N'Polonya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (176, N'PT', N'Portugal', 351, N'Portekiz')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (177, N'PR', N'Puerto Rico', 1787, N'Porto Riko')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (178, N'QA', N'Qatar', 974, N'Katar')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (179, N'RE', N'Reunion', 262, N'Reunion')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (180, N'RO', N'Romania', 40, N'Romanya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (181, N'RU', N'Russia', 70, N'Rusya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (182, N'RW', N'Rwanda', 250, N'Ruanda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (183, N'SH', N'Saint Helena', 290, N'Saint Helena')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (184, N'KN', N'Saint Kitts And Nevis', 1869, N'Saint Kitts ve Nevis')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (185, N'LC', N'Saint Lucia', 1758, N'Saint Lucia')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (186, N'PM', N'Saint Pierre and Miquelon', 508, N'Saint Pierre ve Miquelon')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (187, N'VC', N'Saint Vincent And The Grenadines', 1784, N'Saint Vincent ve Grenadinler')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (188, N'WS', N'Samoa', 684, N'Samoa')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (189, N'SM', N'San Marino', 378, N'San Marino')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (190, N'ST', N'Sao Tome and Principe', 239, N'Sao Tome ve Principe')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (191, N'SA', N'Saudi Arabia', 966, N'Suudi Arabistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (192, N'SN', N'Senegal', 221, N'Senegal')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (193, N'RS', N'Serbia', 381, N'Sırbistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (194, N'SC', N'Seychelles', 248, N'Seyşeller')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (195, N'SL', N'Sierra Leone', 232, N'Sierra Leone')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (196, N'SG', N'Singapore', 65, N'Singapur')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (197, N'SK', N'Slovakia', 421, N'Slovakya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (198, N'SI', N'Slovenia', 386, N'Slovenya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (199, N'XG', N'Smaller Territories of the UK', 44, N'İngiltere''nin Daha Küçük Bölgeleri')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (200, N'SB', N'Solomon Islands', 677, N'Solomon Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (201, N'SO', N'Somalia', 252, N'Somali')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (202, N'ZA', N'South Africa', 27, N'Güney Afrika')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (203, N'GS', N'South Georgia', 0, N'Güney Georgia ve Güney Sandwich Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (204, N'SS', N'South Sudan', 211, N'Güney Sudan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (205, N'ES', N'Spain', 34, N'İspanya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (206, N'LK', N'Sri Lanka', 94, N'Sri Lanka')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (207, N'SD', N'Sudan', 249, N'Sudan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (208, N'SR', N'Suriname', 597, N'Surinam')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (209, N'SJ', N'Svalbard And Jan Mayen Islands', 47, N'Svalbard ve Jan Mayen')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (210, N'SZ', N'Swaziland', 268, N'Esvatini')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (211, N'SE', N'Sweden', 46, N'İsveç')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (212, N'CH', N'Switzerland', 41, N'İsviçre')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (213, N'SY', N'Syria', 963, N'Suriye')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (214, N'TW', N'Taiwan', 886, N'Tayvan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (215, N'TJ', N'Tajikistan', 992, N'Tacikistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (216, N'TZ', N'Tanzania', 255, N'Tanzanya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (217, N'TH', N'Thailand', 66, N'Tayland')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (218, N'TG', N'Togo', 228, N'Togo')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (219, N'TK', N'Tokelau', 690, N'Tokelau')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (220, N'TO', N'Tonga', 676, N'Tonga')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (221, N'TT', N'Trinidad And Tobago', 1868, N'Trinidad ve Tobago')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (222, N'TN', N'Tunisia', 216, N'Tunus')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (223, N'TR', N'Turkey', 90, N'Türkiye')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (224, N'TM', N'Turkmenistan', 7370, N'Türkmenistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (225, N'TC', N'Turks And Caicos Islands', 1649, N'Turks ve Caicos Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (226, N'TV', N'Tuvalu', 688, N'Tuvalu')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (227, N'UG', N'Uganda', 256, N'Uganda')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (228, N'UA', N'Ukraine', 380, N'Ukrayna')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (229, N'AE', N'United Arab Emirates', 971, N'Birleşik Arap Emirlikleri')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (230, N'GB', N'United Kingdom', 44, N'Birleşik Krallık')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (231, N'US', N'United States', 1, N'Amerika Birleşik Devletleri')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (232, N'UM', N'United States Minor Outlying Islands', 1, N'ABD Küçük Harici Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (233, N'UY', N'Uruguay', 598, N'Uruguay')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (234, N'UZ', N'Uzbekistan', 998, N'Özbekistan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (235, N'VU', N'Vanuatu', 678, N'Vanuatu')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (236, N'VA', N'Vatican City State (Holy See)', 39, N'Vatikan')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (237, N'VE', N'Venezuela', 58, N'Venezuela')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (238, N'VN', N'Vietnam', 84, N'Vietnam')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (239, N'VG', N'Virgin Islands (British)', 1284, N'Britanya Virjin Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (240, N'VI', N'Virgin Islands (US)', 1340, N'ABD Virjin Adaları')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (241, N'WF', N'Wallis And Futuna Islands', 681, N'Wallis ve Futuna')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (242, N'EH', N'Western Sahara', 212, N'Batı Sahra')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (243, N'YE', N'Yemen', 967, N'Yemen')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (244, N'YU', N'Yugoslavia', 38, N'Yugoslavya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (245, N'ZM', N'Zambia', 260, N'Zambiya')
INSERT [dbo].[tblUlkeler] ([id], [plaka], [CountryEn], [alankodu], [CountryTr]) VALUES (246, N'ZW', N'Zimbabwe', 263, N'Zimbabve')
